### ISSUE TITLE
nvim TS feature parity + licensing

### ISSUE THREAD

**Issue by xcb-xwii** [Evergreen-lxl/Evergreen.lxl#48]
Some (or most?) of the queries are taken and modified from `nvim-treesitter`.

First problem right now is that we are very much violating their Apache 2.0 license, since it requires the license to be included (duh) and also state any changes.

Second thing that we could address is where we source our query files from, and the parsers to be used alongside them. It would be nice to have it all be from a single, more reputable source.

Hence, maybe we should aim towards greater parity with `nvim-treesitter`? Rough list of what needs to be done if we go ahead with this:
- Use the parsers that they use.
- Use the queries that they use, defining a set of modifications to be done to their queries (since we discard captures such as `@spell`). This might be better than using the queries provided by the parser repos, since they sometimes just do not exist.
- Use the symbol types that they use (which we already most do, so that's not really a problem).

Overall this will let us have a more straightforward framework to add support for more languages, instead of adding one by one. After all, `nvim-treesitter` is much more actively maintained, and it would be nice to have a clearly defined upstream for our queries and parser sources.

This will also allow us to deal with the licensing issues for queries. Since `nvim-treesitter` will basically contain queries and parser sources for most common languages, we can include their license, and make clear that we change the queries to be compatible with Evergreen, and almost not have to worry about licensing anymore.

**Comment by TorchedSammy** [comment]
> Some (or most?) of the queries are taken and modified from nvim-treesitter.

all of them are, actually!

> First problem right now is that we are very much violating their Apache 2.0 license, since it requires the license to be included (duh) and also state any changes.

how would you suggest doing that? do we just include the license in this repo? i'm willing to do that.

> Second thing that we could address is where we source our query files from, and the parsers to be used alongside them. It would be nice to have it all be from a single, more reputable source.

as mentioned, everything comes from `nvim-treesitter`.
the parsers, queries, and all symbols.

> This will also allow us to deal with the licensing issues for queries. Since nvim-treesitter will basically contain queries and parser sources for most common languages, we can include their license, and make clear that we change the queries to be compatible with Evergreen, and almost not have to worry about licensing anymore.

i have no problems with this.

such a small problem with a simple solution really

**Comment by TorchedSammy** [comment]
helix also writes their own treesitter queries, and i'm not sure about any other text editors that support treesitter syntax highlighting

**Comment by xcb-xwii** [comment]
Alright. Since we've confirmed that they're all from nvim-ts, I'll go ahead with the feature parity stuff I have planned. Will be quite a big PR, includes the following:
- nvim's predicates (at minimum, the ones currently used in queries)
- query inheritance
- capture priority
- capture offsets

After this, it should be safe to just copy all of nvim-treesitter's queries, save for a few minor edits.

**Comment by merlindiavova** [comment]
I would happy to contribute to this, I'm currently using a custom script which pulls down `nvim-treesitter` and makes them available to my editor (Pragtical). This is not without minor issues here and there but works really well.
