### ISSUE TITLE
The manifest.json

### ISSUE THREAD

**Issue by jgmdev** [Evergreen-lxl/Evergreen.lxl#57]
After playing around a bit more with #56 this is a working [manifest.json](https://github.com/jgmdev/Evergreen.lxl/blob/PR/meson/manifest.json) file for the plugin manager with working support for:

* x86_64-linux
* x86_64-darwin (aka macos)
* aarch64-darwin (aka macos sillicon)
* x86_64-windows
* x86-windows

Tested and so far working nicely:

![evergreen-manifest-plugins](https://github.com/TorchedSammy/Evergreen.lxl/assets/1702572/7dad9c6c-ec80-46c3-9a36-2d1edf93b6c7)

Got the github workflow working for building ltreesitter and all supported parsers using the meson stuff, was a pain to initially create the manifest.json but that is the price to pay for cross distribution of binaries I guess.

**Comment by TorchedSammy** [comment]
not sure why you're building the parsers on your fork when I already have a builds repo specifically for that, but good work! if you want to pr the manifest I'd merge
